### ISSUE TITLE
Hierarchy - Highlight tasks that do not match rating order

### ISSUE THREAD

**Issue by joesimmons101** [alexpriceonline/hivo#2]
When a user drags a task out of alignment - i.e. one task is moved above another task but the anxiety rating is actually lower - a colour change or visual prompt should come up suggesting it to be moved or a change in anxiety rating. they should also be able to select 'no i want it in this order' so we stop bugging them.

**Comment by alexpricedev** [comment]
No longer relevant for rebuilt
